#!/bin/bash
function install_zint {
  zint_ver=zint-2.3.0
  pushd $HOME
  wget -c http://downloads.sourceforge.net/project/zint/zint/2.3/$zint_ver.src.tar.gz
  tar xvzf ./$zint_ver.src.tar.gz
  cd $zint_ver
  make && make install
  ldconfig
  popd
}
