#!/usr/bin/env ruby

require './servers'
servers = load_servers

output = ENV['HOME']+"/.bash_aliases.servers"

aliases = servers.map do |server|
	"alias ssh-#{server.short_host}=\"#{server.ssh_base}\""
end

File.open(output, 'w+') {|f| f.write(aliases.join("\n"))}

