#!/bin/bash

if [ -z "$VERSION" ]; then
    VERSION=3.0.26    
fi
  
FULLNAME="MySQL-Sandbox-$VERSION"
if [ ! -d $FULLNAME ]; then
	echo "Downloading and extracting..."
	wget "http://launchpad.net/mysql-sandbox/mysql-sandbox-3/mysql-sandbox-3/+download/$FULLNAME.tar.gz"
	tar -xzf "$FULLNAME.tar.gz"
fi

echo "Compiling"
cd $FULLNAME
perl Makefile.PL 
make
make test
make install

echo "Done"
