#!/bin/bash

# base functions
function die {
   echo $@
   exit 1
}

function sudo_check {
  echo "Checking current priviliges:"
  CAN_I_RUN_SUDO=$(sudo -n uptime 2>&1|grep "load"|wc -l)
  if [ ${CAN_I_RUN_SUDO} -gt 0 ]
  then
    echo "It appears that you have already authenticated."
  else
    echo "You do not appear to be authenticated. Please enter your password for $@ when prompted..."
  fi
}


# Install 'wizard'
export SCRIPTS=$HOME/scripts
export RECIPES=$SCRIPTS/server_setup/recipes
export DISTRO=$(lsb_release --codename | awk '{print $2}')

source $RECIPES/setup_*

case $1 in
disks)
  setup_disks
  ;;
db-server)
  setup_percona_server $DISTRO
  ;;
web-server)
  setup_nginx $DISTRO
  ;;
app-server)
  setup_quicktravel_app $DISTRO
  ;;
server)
  echo "setup db, web and app server"
  setup_percona_server $DISTRO
  setup_nginx $DISTRO
  setup_quicktravel_app $DISTRO
  ;;
client)
  setup_client
  ;;
development)
  setup_quicktravel_app
  setup_development
  ;;
*)
  echo "Usage: install_dependencies <client|development|disks|server|db-server|web-server|app-server>"
  echo "client installs requirements to use QuickTravel"
  echo "development installs requirements to develop/test QuickTravel"
  echo "disks formats and mounts new disks"
  echo "server install requirements to run a QuickTravel server"
  echo "server is just an alias for all 3 servers (db, web and app) which can be done individually"
  exit 1
  ;;
esac

