#!/bin/bash

VERSION="MySQL-Sandbox-3.0.25"
if [ ! -d $VERSION ]; then
	echo "Downloading and extracting..."
	wget "http://launchpad.net/mysql-sandbox/mysql-sandbox-3/mysql-sandbox-3/+download/$VERSION.tar.gz"
	tar -xzf "$VERSION.tar.gz"
fi

echo "Compiling"
cd $VERSION
perl Makefile.PL 
make
make test
make install

echo "Done"
