#!/bin/bash

if [ -z "$MYSQL_VERSION" ]; then
    #MYSQL_VERSION=5.5.28
    MYSQL_VERSION=$(mysql -V | awk '{print $5}' | sed -s 's/,//')
fi

if [ -z "$SANDBOX_DIR" ]; then
    #SANDBOX_DIR=/db
    SANDBOX_DIR=`pwd`
fi


EXPECTED_ARGS=2
E_BADARGS=65

if [ ! -d $SANDBOX_DIR ]; then
  echo "Unable to create sandbox - sandbox directory not found, expected $SANDBOX_DIR"
  exit 1
fi

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: install_sandbox sandbox_name sandbox_port"
  exit $E_BADARGS
fi

SANDBOX_BINARY=$SANDBOX_DIR make_sandbox $MYSQL_VERSION -- --sandbox_directory $1 --sandbox_port $2 --upper_directory=$SANDBOX_DIR
