#!/usr/bin/env ruby

command = ENV['COMMAND']
if command.nil?
  puts "COMMAND variable must be specified, e.g.:"
	puts "COMMAND=ls ./run_script_on_servers"
	exit
end

require './servers'
servers = load_servers

def command(string)
	puts ">> #{string}"
  res = `#{string}`
	puts res
end


servers.each do |server|
  ENV['SUDO'] ? server.run_as_sudo(command, ENV['SUDO']) : server.run(command)
end

