#!/usr/bin/env ruby

require 'servers'

command = ENV['COMMAND']
if command.nil?
  puts "COMMAND variable must be specified, e.g.:"
	puts "COMMAND=ls ./run_script_on_servers"
	exit
end

Server.load.each do |server|
  ENV['SUDO'] ? server.ssh_as_sudo(command, ENV['SUDO']) : server.ssh(command)
end

