#!/bin/bash
function setup_quicktravel_app {
  sudo_check "APT"
  
  # solr
  pkg-install "openjdk-7-jre"
  
  # RVM
  RVM_REQS="bash curl git subversion build-essential bison openssl libreadline6 libreadline6-dev zlib1g zlib1g-dev libssl-dev libyaml-dev libxml2-dev libxslt-dev autoconf libc6-dev"
  pkg-install $RVM_REQS

  # QT
  QT_REQS="pdftk fontconfig wbritish imagemagick libmysqld-dev redis-server libpng-dev libz-dev"
  pkg-install $QT_REQS

  # ZINT
  source $SCRIPTS/install_zint/install_zint
  install_zint
}

