#!/usr/bin/env ruby

require_relative 'lib/changelog_checklist'

def ask_version
  print 'Which ChangeLog do you want to format for JIRA checklist? '
  gets.chomp
end

changelog_version = ENV.fetch('VERSION') { ask_version }
puts ChangelogChecklist.new(changelog_version).to_table
